package sed.pricer.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import sed.pricer.data.Shop;
import sed.pricer.data.Category;
import sed.pricer.data.Group;
import sed.pricer.data.Factory;
import sed.pricer.data.Product;
import sed.pricer.data.Price;

import sed.pricer.data.ShopDao;
import sed.pricer.data.CategoryDao;
import sed.pricer.data.GroupDao;
import sed.pricer.data.FactoryDao;
import sed.pricer.data.ProductDao;
import sed.pricer.data.PriceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig groupDaoConfig;
    private final DaoConfig factoryDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig priceDaoConfig;

    private final ShopDao shopDao;
    private final CategoryDao categoryDao;
    private final GroupDao groupDao;
    private final FactoryDao factoryDao;
    private final ProductDao productDao;
    private final PriceDao priceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        factoryDaoConfig = daoConfigMap.get(FactoryDao.class).clone();
        factoryDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        priceDaoConfig = daoConfigMap.get(PriceDao.class).clone();
        priceDaoConfig.initIdentityScope(type);

        shopDao = new ShopDao(shopDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);
        factoryDao = new FactoryDao(factoryDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        priceDao = new PriceDao(priceDaoConfig, this);

        registerDao(Shop.class, shopDao);
        registerDao(Category.class, categoryDao);
        registerDao(Group.class, groupDao);
        registerDao(Factory.class, factoryDao);
        registerDao(Product.class, productDao);
        registerDao(Price.class, priceDao);
    }
    
    public void clear() {
        shopDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        groupDaoConfig.getIdentityScope().clear();
        factoryDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        priceDaoConfig.getIdentityScope().clear();
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public FactoryDao getFactoryDao() {
        return factoryDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public PriceDao getPriceDao() {
        return priceDao;
    }

}
