package sed.pricer.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import sed.pricer.data.Relation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table T_THE_RELATION.
*/
public class RelationDao extends AbstractDao<Relation, Long> {

    public static final String TABLENAME = "T_THE_RELATION";

    /**
     * Properties of entity Relation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Relation_theHolderId = new Property(1, Long.class, "relation_theHolderId", false, "RELATION_THE_HOLDER_ID");
        public final static Property Relation_theItemId = new Property(2, Long.class, "relation_theItemId", false, "RELATION_THE_ITEM_ID");
    };

    private DaoSession daoSession;

    private Query<Relation> theItem_HoldersQuery;
    private Query<Relation> theHolder_ItemsQuery;

    public RelationDao(DaoConfig config) {
        super(config);
    }
    
    public RelationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'T_THE_RELATION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'RELATION_THE_HOLDER_ID' INTEGER," + // 1: relation_theHolderId
                "'RELATION_THE_ITEM_ID' INTEGER);"); // 2: relation_theItemId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'T_THE_RELATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Relation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long relation_theHolderId = entity.getRelation_theHolderId();
        if (relation_theHolderId != null) {
            stmt.bindLong(2, relation_theHolderId);
        }
 
        Long relation_theItemId = entity.getRelation_theItemId();
        if (relation_theItemId != null) {
            stmt.bindLong(3, relation_theItemId);
        }
    }

    @Override
    protected void attachEntity(Relation entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Relation readEntity(Cursor cursor, int offset) {
        Relation entity = new Relation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // relation_theHolderId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // relation_theItemId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Relation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRelation_theHolderId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setRelation_theItemId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Relation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Relation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "holders" to-many relationship of TheItem. */
    public List<Relation> _queryTheItem_Holders(Long relation_theItemId) {
        synchronized (this) {
            if (theItem_HoldersQuery == null) {
                QueryBuilder<Relation> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Relation_theItemId.eq(null));
                theItem_HoldersQuery = queryBuilder.build();
            }
        }
        Query<Relation> query = theItem_HoldersQuery.forCurrentThread();
        query.setParameter(0, relation_theItemId);
        return query.list();
    }

    /** Internal query to resolve the "items" to-many relationship of TheHolder. */
    public List<Relation> _queryTheHolder_Items(Long relation_theHolderId) {
        synchronized (this) {
            if (theHolder_ItemsQuery == null) {
                QueryBuilder<Relation> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Relation_theHolderId.eq(null));
                theHolder_ItemsQuery = queryBuilder.build();
            }
        }
        Query<Relation> query = theHolder_ItemsQuery.forCurrentThread();
        query.setParameter(0, relation_theHolderId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTheItemDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTheHolderDao().getAllColumns());
            builder.append(" FROM T_THE_RELATION T");
            builder.append(" LEFT JOIN T_THE_ITEM T0 ON T.'RELATION_THE_ITEM_ID'=T0.'_id'");
            builder.append(" LEFT JOIN T_THE_HOLDER T1 ON T.'RELATION_THE_HOLDER_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Relation loadCurrentDeep(Cursor cursor, boolean lock) {
        Relation entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TheItem theItem = loadCurrentOther(daoSession.getTheItemDao(), cursor, offset);
        entity.setTheItem(theItem);
        offset += daoSession.getTheItemDao().getAllColumns().length;

        TheHolder theHolder = loadCurrentOther(daoSession.getTheHolderDao(), cursor, offset);
        entity.setTheHolder(theHolder);

        return entity;    
    }

    public Relation loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Relation> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Relation> list = new ArrayList<Relation>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Relation> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Relation> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
