package sed.pricer.data;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table T_SHOPS.
 */
public class Shop implements Serializable{

    private Long id;
    private String name;

    // KEEP FIELDS - put your custom fields here
    String someField;
	private static final long serialVersionUID = -4852743856928121426L;
    // KEEP FIELDS END

    public Shop() {
    }

    public Shop(Long id) {
        this.id = id;
    }

    public Shop(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "Shop [id=" + id + ", name=" + name + ", someField=" + someField
				+ "]";
	}
    // KEEP METHODS END

}
